-- SEED CLASS SUBJECTS
-- Cabang Bekasi, Jakarta, LMS DB

INSERT INTO class_subjects (id_kelas, id_mapel, id_guru_mutlak, durasi_jp)
SELECT c.id_kelas, s.id_mapel, t.id_guru, data.durasi_jp
FROM (
VALUES
  ('XI OTKP 1', 'OTK Kepegawaian', 14, 2),
  ('XI OTKP 2', 'OTK Kepegawaian', 14, 2),
  ('XII OTKP 1', 'OTK Kepegawaian', 14, 3),
  ('XII OTKP 2', 'OTK Kepegawaian', 14, 3),
  ('XI AKL 1', 'Adm Pajak', 14, 2),
  ('XII AKL 1', 'Adm Pajak', 14, 2),
  ('X OTKP 2', 'Matematika', 15, 5),
  ('X TKRO 1', 'Matematika', 15, 5),
  ('X TKRO 2', 'Matematika', 15, 5),
  ('X TBSM 1', 'Matematika', 15, 5),
  ('X TBSM 2', 'Matematika', 15, 5),
  ('XI AKL 1', 'Matematika', 15, 5),
  ('XI TBSM 1', 'Matematika', 15, 5),
  ('XI TBSM 2', 'Matematika', 15, 5),
  ('XII AKL 1', 'Matematika', 15, 5),
  ('XII TKJ 1', 'Matematika', 15, 5),
  ('XII TKJ 2', 'Matematika', 15, 5),
  ('XII TKRO 1', 'Matematika', 15, 5),
  ('XII TKRO 2', 'Matematika', 15, 5),
  ('XI TBSM 1', 'Main. Mesin Sepeda Motor', 16, 4),
  ('XI TBSM 2', 'Main. Mesin Sepeda Motor', 16, 4),
  ('XII TBSM 1', 'Main. Mesin Sepeda Motor', 16, 5),
  ('XII TBSM 2', 'Main. Mesin Sepeda Motor', 16, 5),
  ('X TKRO 1', 'TDO', 16, 4),
  ('XI TBSM 1', 'Main. Sasis Sepeda Motor', 16, 4),
  ('XI TBSM 2', 'Main. Sasis Sepeda Motor', 16, 4),
  ('XII TBSM 1', 'Main. Sasis Sepeda Motor', 16, 5),
  ('XII TBSM 2', 'Main. Sasis Sepeda Motor', 16, 5),
  ('XI TBSM 1', 'Kelistrikan Sepeda Motor', 16, 4),
  ('XI TBSM 2', 'Kelistrikan Sepeda Motor', 16, 4),
  ('XII TBSM 1', 'Kelistrikan Sepeda Motor', 16, 5),
  ('XII TBSM 2', 'Kelistrikan Sepeda Motor', 16, 5),
  ('X AKL 1', 'Bahasa Inggris', 17, 4),
  ('XI TKRO 1', 'Bahasa Inggris', 17, 4),
  ('XI TBSM 1', 'Bahasa Inggris', 17, 4),
  ('XI TBSM 2', 'Bahasa Inggris', 17, 4),
  ('XII AKL 1', 'Bahasa Inggris', 17, 4),
  ('XII OTKP 1', 'Bahasa Inggris', 17, 4),
  ('XII OTKP 2', 'Bahasa Inggris', 17, 4),
  ('XII TKJ 1', 'Bahasa Inggris', 17, 4),
  ('XII TKJ 2', 'Bahasa Inggris', 17, 4),
  ('X OTKP 1', 'Pendidikan Agama Islam', 18, 2),
  ('X TKJ 2', 'Pendidikan Agama Islam', 18, 2),
  ('X TKRO 1', 'Pendidikan Agama Islam', 18, 2),
  ('XI TKJ 1', 'Pendidikan Agama Islam', 18, 2),
  ('XI TKJ 2', 'Pendidikan Agama Islam', 18, 2),
  ('XI TKRO 1', 'Pendidikan Agama Islam', 18, 2),
  ('XI TBSM 1', 'Pendidikan Agama Islam', 18, 2),
  ('XI TBSM 2', 'Pendidikan Agama Islam', 18, 2),
  ('XII TKJ 1', 'Pendidikan Agama Islam', 18, 2),
  ('XII TKJ 2', 'Pendidikan Agama Islam', 18, 2),
  ('XII TKRO 1', 'Pendidikan Agama Islam', 18, 2),
  ('XII TKRO 2', 'Pendidikan Agama Islam', 18, 2),
  ('XII TBSM 1', 'Pendidikan Agama Islam', 18, 2),
  ('XII TBSM 2', 'Pendidikan Agama Islam', 18, 2),
  ('XII TKJ 1', 'Teknik Infrastruktur Jaringan', 19, 4),
  ('XII TKJ 2', 'Teknik Infrastruktur Jaringan', 19, 4),
  ('XI AKL 1', 'KKA / Coding', 19, 2),
  ('XI OTKP 1', 'KKA / Coding', 19, 2),
  ('XI OTKP 2', 'KKA / Coding', 19, 2),
  ('XI TKJ 1', 'KKA / Coding', 19, 2),
  ('XI TKJ 2', 'KKA / Coding', 19, 2),
  ('XI TKRO 1', 'KKA / Coding', 19, 2),
  ('XI TBSM 1', 'KKA / Coding', 19, 2),
  ('XI TBSM 2', 'KKA / Coding', 19, 2),
  ('XII TKJ 1', 'Tek Layanan Jaringan', 19, 4),
  ('XII TKJ 2', 'Tek Layanan Jaringan', 19, 4),
  ('X TKJ 2', 'Sejarah Indonesia', 27, 2),
  ('X TKRO 1', 'Sejarah Indonesia', 11, 2),
  ('X TKRO 2', 'Sejarah Indonesia', 11, 2),
  ('XI TKRO 1', 'Sejarah Indonesia', 11, 2),
  ('XI TBSM 1', 'Sejarah Indonesia', 11, 2),
  ('XI TBSM 2', 'Sejarah Indonesia', 11, 2),
  ('XII TKRO 1', 'Sejarah Indonesia', 27, 2),
  ('XII TKRO 2', 'Sejarah Indonesia', 27, 2),
  ('XII TBSM 1', 'Sejarah Indonesia', 27, 2),
  ('XII TBSM 2', 'Sejarah Indonesia', 27, 2),
  ('XII TKRO 1', 'Main. Mesin Kendaraan', 20, 5),
  ('XII TKRO 2', 'Main. Mesin Kendaraan', 20, 5),
  ('XII TKRO 1', 'Main. Sasis Kendaraan', 20, 5),
  ('XII TKRO 2', 'Main. Sasis Kendaraan', 20, 5),
  ('X TKRO 1', 'PDTO', 20, 4),
  ('XI TKRO 1', 'PDTO', 20, 4),
  ('X TBSM 1', 'TDO', 20, 4),
  ('XI TKRO 1', 'Kelistrikan Kendaraan Ringan', 20, 4),
  ('XII TKRO 1', 'Kelistrikan Kendaraan Ringan', 20, 5),
  ('XII TKRO 2', 'Kelistrikan Kendaraan Ringan', 20, 5),
  ('X TKRO 1', 'Gambar Teknik', 21, 3),
  ('X TKRO 2', 'Gambar Teknik', 21, 3),
  ('X TBSM 1', 'Gambar Teknik', 21, 3),
  ('X TBSM 2', 'Gambar Teknik', 21, 3),
  ('X TKRO 2', 'TDO', 21, 4),
  ('X AKL 1', 'K3LH', 21, 2),
  ('X OTKP 1', 'K3LH', 21, 2),
  ('X OTKP 2', 'K3LH', 21, 2),
  ('X TKJ 2', 'K3LH', 21, 3),
  ('X TKRO 1', 'K3LH', 21, 2),
  ('X TKRO 2', 'K3LH', 21, 2),
  ('X TBSM 1', 'K3LH', 21, 2),
  ('X TBSM 2', 'K3LH', 21, 2),
  ('X TBSM 1', 'PDTO', 21, 4),
  ('X OTKP 1', 'Bahasa Indonesia', 22, 3),
  ('X TKJ 1', 'Bahasa Indonesia', 22, 3),
  ('X TKRO 1', 'Bahasa Indonesia', 22, 3),
  ('X TBSM 1', 'Bahasa Indonesia', 22, 3),
  ('XI OTKP 1', 'Bahasa Indonesia', 22, 3),
  ('XI OTKP 2', 'Bahasa Indonesia', 22, 3),
  ('XI TKJ 1', 'Bahasa Indonesia', 22, 3),
  ('XI TKJ 2', 'Bahasa Indonesia', 22, 3),
  ('XII TKJ 1', 'Bahasa Indonesia', 22, 3),
  ('XII TKJ 2', 'Bahasa Indonesia', 22, 3),
  ('XII TKRO 1', 'Bahasa Indonesia', 22, 3),
  ('XII TKRO 2', 'Bahasa Indonesia', 22, 3),
  ('XII TBSM 1', 'Bahasa Indonesia', 22, 3),
  ('XII TBSM 2', 'Bahasa Indonesia', 22, 3),
  ('X AKL 1', 'Spreadsheet', 22, 2),
  ('XI AKL 1', 'AK Keuangan', 22, 2),
  ('X AKL 1', 'Pendidikan Agama Islam', 3, 2),
  ('X TKJ 1', 'Pendidikan Agama Islam', 3, 2),
  ('X TKRO 2', 'Pendidikan Agama Islam', 3, 2),
  ('X TBSM 2', 'Pendidikan Agama Islam', 3, 2),
  ('XI AKL 1', 'Pendidikan Agama Islam', 18, 2),
  ('XI OTKP 1', 'Pendidikan Agama Islam', 18, 2),
  ('XI OTKP 2', 'Pendidikan Agama Islam', 18, 2),
  ('XII AKL 1', 'Pendidikan Agama Islam', 18, 2),
  ('XII OTKP 1', 'Pendidikan Agama Islam', 18, 2),
  ('XII OTKP 2', 'Pendidikan Agama Islam', 18, 2),
  ('X TKJ 1', 'Dasar Jaringan Komputer', 23, 4),
  ('X TKJ 2', 'Dasar Jaringan Komputer', 23, 4),
  ('XII TKJ 1', 'Wide Area Network (WAN)', 23, 3),
  ('XII TKJ 2', 'Wide Area Network (WAN)', 23, 3),
  ('XI TKJ 1', 'Teknik Infrastruktur Jaringan', 23, 3),
  ('XI TKJ 2', 'Teknik Infrastruktur Jaringan', 23, 3),
  ('XI TKJ 1', 'Adm Sistem Jaringan', 23, 4),
  ('XI TKJ 2', 'Adm Sistem Jaringan', 23, 4),
  ('XII TKJ 1', 'Adm Sistem Jaringan', 23, 4),
  ('XII TKJ 2', 'Adm Sistem Jaringan', 23, 4),
  ('X TKRO 1', 'Informatika', 23, 3),
  ('X TKRO 2', 'Informatika', 23, 3),
  ('X TBSM 1', 'Informatika', 23, 3),
  ('X TBSM 2', 'Informatika', 23, 3),
  ('X TKJ 1', 'Tek Jaringan Komputer', 24, 3),
  ('X TKJ 2', 'Tek Jaringan Komputer', 24, 3),
  ('X TKJ 1', 'Bisnis Teknologi Informasi', 24, 3),
  ('X TKJ 2', 'Bisnis Teknologi Informasi', 24, 3),
  ('XI TKJ 1', 'Tek Layanan Jaringan', 24, 3),
  ('XI TKJ 2', 'Tek Layanan Jaringan', 24, 3),
  ('XI TKJ 1', 'Wide Area Network (WAN)', 24, 3),
  ('XI TKJ 2', 'Wide Area Network (WAN)', 24, 3),
  ('X AKL 1', 'Informatika', 24, 3),
  ('X OTKP 1', 'Informatika', 24, 3),
  ('X OTKP 2', 'Informatika', 24, 3),
  ('X TKJ 1', 'Informatika', 24, 3),
  ('X TKJ 2', 'Informatika', 24, 3),
  ('X OTKP 1', 'Teknologi Perkantoran', 25, 3),
  ('X OTKP 2', 'Teknologi Perkantoran', 25, 3),
  ('X OTKP 1', 'OTK Humas', 25, 3),
  ('X OTKP 2', 'OTK Humas', 25, 3),
  ('XI OTKP 1', 'OTK Sarpras', 25, 2),
  ('XI OTKP 2', 'OTK Sarpras', 25, 2),
  ('XII OTKP 1', 'OTK Sarpras', 25, 4),
  ('XII OTKP 2', 'OTK Sarpras', 25, 4),
  ('XI OTKP 1', 'Kearsipan', 25, 2),
  ('XI OTKP 2', 'Kearsipan', 25, 2),
  ('X TKRO 1', 'Bahasa Inggris', 26, 4),
  ('X TKRO 2', 'Bahasa Inggris', 26, 4),
  ('X TBSM 1', 'Bahasa Inggris', 26, 4),
  ('X TBSM 2', 'Bahasa Inggris', 26, 4),
  ('XI TKJ 1', 'Bahasa Inggris', 26, 4),
  ('XI TKJ 2', 'Bahasa Inggris', 26, 4),
  ('X TKJ 2', 'PPKn', 27, 2),
  ('X TKRO 1', 'PPKn', 27, 2),
  ('X TKRO 2', 'PPKn', 27, 2),
  ('X TBSM 1', 'PPKn', 27, 2),
  ('XII TKRO 2', 'PPKn', 27, 2),
  ('XII TBSM 1', 'PPKn', 27, 2),
  ('XII TBSM 2', 'PPKn', 27, 2),
  ('X AKL 1', 'Sejarah Indonesia', 27, 2),
  ('X OTKP 1', 'Sejarah Indonesia', 27, 2),
  ('X OTKP 2', 'Sejarah Indonesia', 27, 2),
  ('X TKJ 1', 'Sejarah Indonesia', 27, 2),
  ('X OTKP 1', 'Adm Umum', 28, 2),
  ('X OTKP 2', 'Adm Umum', 28, 2),
  ('XI AKL 1', 'Adm Umum', 28, 2),
  ('X AKL 1', 'IPAS', 28, 2),
  ('X OTKP 1', 'IPAS', 28, 2),
  ('X OTKP 2', 'IPAS', 28, 2),
  ('X TKJ 1', 'IPAS', 28, 2),
  ('X TKJ 2', 'IPAS', 28, 2),
  ('X TKRO 1', 'IPAS', 28, 2),
  ('X TKRO 2', 'IPAS', 28, 2),
  ('X TBSM 1', 'IPAS', 28, 2),
  ('X TBSM 2', 'IPAS', 28, 2),
  ('X AKL 1', 'Komputer Akuntansi', 30, 2),
  ('XI AKL 1', 'Komputer Akuntansi', 30, 2),
  ('XII AKL 1', 'Komputer Akuntansi', 30, 3),
  ('X AKL 1', 'Seni Budaya', 31, 2),
  ('X OTKP 1', 'Seni Budaya', 31, 2),
  ('X OTKP 2', 'Seni Budaya', 31, 2),
  ('X TKJ 1', 'Seni Budaya', 31, 2),
  ('X TKJ 2', 'Seni Budaya', 31, 2),
  ('X TKRO 1', 'Seni Budaya', 31, 2),
  ('X TKRO 2', 'Seni Budaya', 31, 2),
  ('X TBSM 1', 'Seni Budaya', 31, 2),
  ('X TBSM 2', 'Seni Budaya', 31, 2),
  ('XI AKL 1', 'Seni Budaya', 31, 2),
  ('XI OTKP 1', 'Seni Budaya', 31, 2),
  ('XI OTKP 2', 'Seni Budaya', 31, 2),
  ('XI TKJ 1', 'Seni Budaya', 31, 2),
  ('XI TKJ 2', 'Seni Budaya', 31, 2),
  ('XI TKRO 1', 'Seni Budaya', 31, 2),
  ('XI TBSM 1', 'Seni Budaya', 31, 2),
  ('XI TBSM 2', 'Seni Budaya', 31, 2),
  ('XII AKL 1', 'Seni Budaya', 31, 2),
  ('XII OTKP 1', 'Seni Budaya', 31, 2),
  ('XII OTKP 2', 'Seni Budaya', 31, 2),
  ('XII TKJ 1', 'Seni Budaya', 31, 2),
  ('XII TKJ 2', 'Seni Budaya', 31, 2),
  ('XII TKRO 1', 'Seni Budaya', 31, 2),
  ('XII TKRO 2', 'Seni Budaya', 31, 2),
  ('XII TBSM 1', 'Seni Budaya', 31, 2),
  ('XII TBSM 2', 'Seni Budaya', 31, 2),
  ('X OTKP 1', 'Bahasa Inggris', 32, 4),
  ('X OTKP 2', 'Bahasa Inggris', 32, 4),
  ('X TKJ 1', 'Bahasa Inggris', 32, 4),
  ('X TKJ 2', 'Bahasa Inggris', 32, 4),
  ('XI OTKP 1', 'Bahasa Inggris', 32, 4),
  ('XI OTKP 2', 'Bahasa Inggris', 32, 4),
  ('XII TKRO 1', 'Bahasa Inggris', 32, 4),
  ('XII TKRO 2', 'Bahasa Inggris', 32, 4),
  ('XII TBSM 1', 'Bahasa Inggris', 32, 4),
  ('XII TBSM 2', 'Bahasa Inggris', 32, 4),
  ('X AKL 1', 'Matematika', 33, 5),
  ('X OTKP 1', 'Matematika', 33, 5),
  ('X TKJ 1', 'Matematika', 33, 5),
  ('X TKJ 2', 'Matematika', 33, 5),
  ('XI TKRO 1', 'Matematika', 33, 5),
  ('X AKL 1', 'Bahasa Indonesia', 34, 3),
  ('XI AKL 1', 'Bahasa Indonesia', 34, 2),
  ('XI TKRO 1', 'Bahasa Indonesia', 34, 3),
  ('XI TBSM 1', 'Bahasa Indonesia', 34, 3),
  ('XI TBSM 2', 'Bahasa Indonesia', 34, 3),
  ('XII AKL 1', 'Bahasa Indonesia', 34, 3),
  ('XII OTKP 1', 'Bahasa Indonesia', 34, 3),
  ('XII OTKP 2', 'Bahasa Indonesia', 34, 3),
  ('X TBSM 2', 'TDO', 35, 4),
  ('X TKRO 2', 'PDTO', 35, 4),
  ('X TKJ 1', 'K3LH', 35, 3),
  ('XI TBSM 1', 'Main. Mesin Kendaraan', 35, 5),
  ('XI TBSM 2', 'Main. Mesin Kendaraan', 35, 5),
  ('X AKL 1', 'PPKn', 5, 2),
  ('X AKL 1', 'Penjasorkes', 3, 2),
  ('X AKL 1', 'Etika Profesi', 11, 2),
  ('X AKL 1', 'Akuntansi Dasar', 7, 3),
  ('X AKL 1', 'Perbankan Dasar', 11, 2),
  ('X OTKP 1', 'PPKn', 12, 2),
  ('X OTKP 1', 'Penjasorkes', 9, 2),
  ('X OTKP 1', 'Korespondensi', 8, 3),
  ('X OTKP 2', 'PPKn', 12, 2),
  ('X OTKP 2', 'Bahasa Indonesia', 13, 3),
  ('X OTKP 2', 'Penjasorkes', 10, 2),
  ('X OTKP 2', 'Korespondensi', 8, 3),
  ('X TKJ 1', 'PPKn', 5, 2),
  ('X TKJ 1', 'Penjasorkes', 10, 2),
  ('X TKJ 2', 'Bahasa Indonesia', 13, 3),
  ('X TKJ 2', 'Penjasorkes', 9, 2),
  ('X TKRO 1', 'Penjasorkes', 3, 2),
  ('X TKRO 2', 'Bahasa Indonesia', 13, 3),
  ('X TKRO 2', 'Penjasorkes', 3, 2),
  ('X TBSM 1', 'Penjasorkes', 9, 2),
  ('X TBSM 1', 'Sejarah Indonesia', 11, 2),
  ('X TBSM 2', 'PPKn', 5, 2),
  ('X TBSM 2', 'Bahasa Indonesia', 13, 3),
  ('X TBSM 2', 'Penjasorkes', 10, 2),
  ('X TBSM 2', 'Sejarah Indonesia', 11, 2),
  ('XI AKL 1', 'PPKn', 12, 2),
  ('XI AKL 1', 'Penjasorkes', 10, 2),
  ('XI AKL 1', 'Sejarah Indonesia', 11, 2),
  ('XI AKL 1', 'Ekonomi Bisnis', 7, 2),
  ('XI AKL 1', 'Praktikum Akuntansi Perusahaan Jasa, Dagang dan Manufaktur', 7, 2),
  ('XI AKL 1', 'AK Lembaga', 7, 2),
  ('XI AKL 1', 'PKK', 6, 3),
  ('XI OTKP 1', 'PPKn', 12, 2),
  ('XI OTKP 1', 'Penjasorkes', 9, 2),
  ('XI OTKP 1', 'Sejarah Indonesia', 11, 2),
  ('XI OTKP 1', 'Matematika', 2, 5),
  ('XI OTKP 1', 'OTK Keuangan', 7, 2),
  ('XI OTKP 1', 'OTK Humas', 8, 3),
  ('XI OTKP 1', 'PKK', 6, 3),
  ('XI OTKP 2', 'PPKn', 5, 2),
  ('XI OTKP 2', 'Penjasorkes', 3, 2),
  ('XI OTKP 2', 'Sejarah Indonesia', 11, 2),
  ('XI OTKP 2', 'Matematika', 4, 5),
  ('XI OTKP 2', 'OTK Keuangan', 7, 2),
  ('XI OTKP 2', 'OTK Humas', 8, 3),
  ('XI OTKP 2', 'PKK', 6, 3),
  ('XI TKJ 1', 'PPKn', 5, 2),
  ('XI TKJ 1', 'Penjasorkes', 3, 2),
  ('XI TKJ 1', 'Sejarah Indonesia', 11, 2),
  ('XI TKJ 1', 'Matematika', 4, 5),
  ('XI TKJ 1', 'PKK', 6, 3),
  ('XI TKJ 2', 'PPKn', 12, 2),
  ('XI TKJ 2', 'Penjasorkes', 9, 2),
  ('XI TKJ 2', 'Sejarah Indonesia', 11, 2),
  ('XI TKJ 2', 'Matematika', 2, 5),
  ('XI TKJ 2', 'PKK', 6, 3),
  ('XI TKRO 1', 'PPKn', 12, 2),
  ('XI TKRO 1', 'Penjasorkes', 10, 2),
  ('XI TKRO 1', 'PKK', 6, 3),
  ('XI TBSM 1', 'PPKn', 5, 2),
  ('XI TBSM 1', 'Penjasorkes', 9, 2),
  ('XI TBSM 1', 'PKK', 11, 3),
  ('XI TBSM 2', 'PPKn', 12, 2),
  ('XI TBSM 2', 'Penjasorkes', 3, 2),
  ('XI TBSM 2', 'PKK', 11, 3),
  ('XII AKL 1', 'PPKn', 12, 2),
  ('XII AKL 1', 'Penjasorkes', 3, 2),
  ('XII AKL 1', 'Sejarah Indonesia', 11, 2),
  ('XII AKL 1', 'Praktikum Akuntansi Perusahaan Jasa, Dagang dan Manufaktur', 7, 4),
  ('XII AKL 1', 'AK Lembaga', 7, 3),
  ('XII AKL 1', 'AK Keuangan', 22, 3),
  ('XII AKL 1', 'PKK', 6, 3),
  ('XII OTKP 1', 'PPKn', 5, 2),
  ('XII OTKP 1', 'Penjasorkes', 9, 2),
  ('XII OTKP 1', 'Sejarah Indonesia', 11, 2),
  ('XII OTKP 1', 'Matematika', 2, 5),
  ('XII OTKP 1', 'OTK Keuangan', 7, 4),
  ('XII OTKP 1', 'OTK Humas', 8, 4),
  ('XII OTKP 1', 'PKK', 6, 3),
  ('XII OTKP 2', 'PPKn', 5, 2),
  ('XII OTKP 2', 'Penjasorkes', 10, 2),
  ('XII OTKP 2', 'Sejarah Indonesia', 11, 2),
  ('XII OTKP 2', 'Matematika', 4, 5),
  ('XII OTKP 2', 'OTK Keuangan', 7, 4),
  ('XII OTKP 2', 'OTK Humas', 8, 4),
  ('XII OTKP 2', 'PKK', 6, 3),
  ('XII TKJ 1', 'PPKn', 12, 2),
  ('XII TKJ 1', 'Penjasorkes', 10, 2),
  ('XII TKJ 1', 'Sejarah Indonesia', 11, 2),
  ('XII TKJ 1', 'PKK', 6, 3),
  ('XII TKJ 2', 'PPKn', 12, 2),
  ('XII TKJ 2', 'Penjasorkes', 9, 2),
  ('XII TKJ 2', 'Sejarah Indonesia', 11, 2),
  ('XII TKJ 2', 'PKK', 6, 3),
  ('XII TKRO 1', 'PPKn', 5, 2),
  ('XII TKRO 1', 'Penjasorkes', 3, 2),
  ('XII TKRO 1', 'PKK', 11, 3),
  ('XII TKRO 2', 'Penjasorkes', 3, 2),
  ('XII TKRO 2', 'PKK', 6, 3),
  ('XII TBSM 1', 'Penjasorkes', 9, 2),
  ('XII TBSM 1', 'Matematika', 4, 5),
  ('XII TBSM 1', 'PKK', 11, 3),
  ('XII TBSM 2', 'Penjasorkes', 10, 2),
  ('XII TBSM 2', 'Matematika', 2, 5),
  ('XII TBSM 2', 'PKK', 6, 3)
) AS data(nama_kelas, nama_mapel, kode_guru, durasi_jp)
JOIN classes c ON c.nama_kelas = data.nama_kelas
JOIN subjects s ON s.nama_mapel = data.nama_mapel
LEFT JOIN teachers t ON t.kode_guru = data.kode_guru;
