-- ============================================================
-- SEED DATA: CLASS SUBJECT ALLOCATIONS
-- ============================================================

INSERT INTO classes (nama_kelas, shift_operasional, tingkat, jurusan)
VALUES ('XI TKR 2', 'SIANG', 'XI', 'TKR')
ON CONFLICT (nama_kelas) DO NOTHING;

TRUNCATE TABLE class_subjects CASCADE;

INSERT INTO class_subjects (id_kelas, id_mapel, id_guru, durasi_jp)
SELECT c.id_kelas, s.id_mapel, t.id_guru, data.durasi_jp
FROM (VALUES
  ('XI OTKP 1', 'OTK Kepegawaian', 14, 2),
  ('XI OTKP 2', 'OTK Kepegawaian', 14, 2),
  ('XII OTKP 1', 'OTK Kepegawaian', 14, 3),
  ('XII OTKP 2', 'OTK Kepegawaian', 14, 3),
  ('XI AK 1', 'Adm Pajak', 14, 2),
  ('XII AK 1', 'Adm Pajak', 14, 2),
  ('X OTKP 2', 'Matematika', 15, 5),
  ('X TKR 1', 'Matematika', 15, 5),
  ('X TKR 2', 'Matematika', 15, 5),
  ('X TSM 1', 'Matematika', 15, 5),
  ('X TSM 2', 'Matematika', 15, 5),
  ('XI AK 1', 'Matematika', 15, 5),
  ('XI TSM 1', 'Matematika', 15, 5),
  ('XI TSM 2', 'Matematika', 15, 5),
  ('XII AK 1', 'Matematika', 15, 5),
  ('XII TKJ 1', 'Matematika', 15, 5),
  ('XII TKJ 2', 'Matematika', 15, 5),
  ('XII TKR 1', 'Matematika', 15, 5),
  ('XII TKR 2', 'Matematika', 15, 5),
  ('XI TSM 1', 'Kelistrikan Kendaraan', 16, 5),
  ('XI TSM 2', 'Kelistrikan Kendaraan', 16, 5),
  ('XII TSM 1', 'Main. Mesin Sepeda Motor', 16, 5),
  ('XII TSM 2', 'Main. Mesin Sepeda Motor', 16, 5),
  ('X TKR 1', 'TDO', 16, 4),
  ('XI TSM 1', 'Main. Sasis Sepeda Motor', 16, 4),
  ('XI TSM 2', 'Main. Sasis Sepeda Motor', 16, 4),
  ('XII TSM 1', 'Main. Sasis Sepeda Motor', 16, 5),
  ('XII TSM 2', 'Main. Sasis Sepeda Motor', 16, 5),
  ('XI TSM 1', 'Kelistrikan Sepeda Motor', 16, 4),
  ('XI TSM 2', 'Kelistrikan Sepeda Motor', 16, 4),
  ('XII TSM 1', 'Kelistrikan Sepeda Motor', 16, 5),
  ('XII TSM 2', 'Kelistrikan Sepeda Motor', 16, 5),
  ('X AK 1', 'Bahasa Inggris', 17, 4),
  ('XI TKR 1', 'Bahasa Inggris', 17, 4),
  ('XI TKR 2', 'Bahasa Inggris', 17, 4),
  ('XI TSM 1', 'Bahasa Inggris', 17, 4),
  ('XI TSM 2', 'Bahasa Inggris', 17, 4),
  ('XII AK 1', 'Bahasa Inggris', 17, 4),
  ('XII OTKP 1', 'Bahasa Inggris', 17, 4),
  ('XII OTKP 2', 'Bahasa Inggris', 17, 4),
  ('XII TKJ 1', 'Bahasa Inggris', 17, 4),
  ('XII TKJ 2', 'Bahasa Inggris', 17, 4),
  ('X OTKP 1', 'Pendidikan Agama dan Budi Pekerti', 18, 2),
  ('X TKJ 2', 'Pendidikan Agama dan Budi Pekerti', 18, 2),
  ('X TKR 1', 'Pendidikan Agama dan Budi Pekerti', 18, 2),
  ('XI TKJ 1', 'Pendidikan Agama dan Budi Pekerti', 18, 2),
  ('XI TKJ 2', 'Pendidikan Agama dan Budi Pekerti', 18, 2),
  ('XI TKR 1', 'Pendidikan Agama dan Budi Pekerti', 18, 2),
  ('XI TKR 2', 'Pendidikan Agama dan Budi Pekerti', 18, 2),
  ('XI TSM 1', 'Pendidikan Agama dan Budi Pekerti', 18, 2),
  ('XI TSM 2', 'Pendidikan Agama dan Budi Pekerti', 18, 2),
  ('XII TKJ 1', 'Pendidikan Agama dan Budi Pekerti', 18, 2),
  ('XII TKJ 2', 'Pendidikan Agama dan Budi Pekerti', 18, 2),
  ('XII TKR 1', 'Pendidikan Agama dan Budi Pekerti', 18, 2),
  ('XII TKR 2', 'Pendidikan Agama dan Budi Pekerti', 18, 2),
  ('XII TSM 1', 'Pendidikan Agama dan Budi Pekerti', 18, 2),
  ('XII TSM 2', 'Pendidikan Agama dan Budi Pekerti', 18, 2),
  ('XII TKJ 1', 'Teknologi Infrastruktur Jaringan', 19, 4),
  ('XII TKJ 2', 'Teknologi Infrastruktur Jaringan', 19, 4),
  ('XI AK 1', 'KKA / Coding', 19, 2),
  ('XI OTKP 1', 'KKA / Coding', 19, 2),
  ('XI OTKP 2', 'KKA / Coding', 19, 2),
  ('XI TKJ 1', 'KKA / Coding', 19, 2),
  ('XI TKJ 2', 'KKA / Coding', 19, 2),
  ('XI TKR 1', 'KKA / Coding', 19, 2),
  ('XI TKR 2', 'KKA / Coding', 19, 2),
  ('XI TSM 1', 'KKA / Coding', 19, 2),
  ('XI TSM 2', 'KKA / Coding', 19, 2),
  ('XII TKJ 1', 'Teknologi Layanan Jaringan', 19, 4),
  ('XII TKJ 2', 'Teknologi Layanan Jaringan', 19, 4),
  ('X TKJ 2', 'Sejarah Indonesia', 20, 2),
  ('X TKR 1', 'Sejarah Indonesia', 20, 2),
  ('X TKR 2', 'Sejarah Indonesia', 20, 2),
  ('XI TKR 1', 'Sejarah Indonesia', 20, 2),
  ('XI TKR 2', 'Sejarah Indonesia', 20, 2),
  ('XI TSM 1', 'Sejarah Indonesia', 20, 2),
  ('XI TSM 2', 'Sejarah Indonesia', 20, 2),
  ('XII TKR 1', 'Sejarah Indonesia', 20, 2),
  ('XII TKR 2', 'Sejarah Indonesia', 20, 2),
  ('XII TSM 1', 'Sejarah Indonesia', 20, 2),
  ('XII TSM 2', 'Sejarah Indonesia', 20, 2),
  ('XII TKR 1', 'Main. Mesin Kendaraan', 21, 5),
  ('XII TKR 2', 'Main. Mesin Kendaraan', 21, 5),
  ('XII TKR 1', 'Main. Sasis Kendaraan', 21, 5),
  ('XII TKR 2', 'Main. Sasis Kendaraan', 21, 5),
  ('X TKR 1', 'PDTO', 21, 4),
  ('XI TKR 1', 'PDTO', 21, 4),
  ('XI TKR 2', 'PDTO', 21, 4),
  ('X TSM 1', 'TDO', 21, 4),
  ('XI TKR 1', 'Kelistrikan Kendaraan Ringan', 21, 4),
  ('XI TKR 2', 'Kelistrikan Kendaraan Ringan', 21, 4),
  ('XII TKR 1', 'Kelistrikan Kendaraan Ringan', 21, 5),
  ('XII TKR 2', 'Kelistrikan Kendaraan Ringan', 21, 5),
  ('X TKR 1', 'Gambar Teknik', 22, 3),
  ('X TKR 2', 'Gambar Teknik', 22, 3),
  ('X TSM 1', 'Gambar Teknik', 22, 3),
  ('X TSM 2', 'Gambar Teknik', 22, 3),
  ('X TKR 2', 'TDO', 22, 4),
  ('X AK 1', 'K3LH', 22, 2),
  ('X OTKP 1', 'K3LH', 22, 2),
  ('X OTKP 2', 'K3LH', 22, 2),
  ('X TKJ 2', 'K3LH', 22, 3),
  ('X TKR 1', 'K3LH', 22, 2),
  ('X TKR 2', 'K3LH', 22, 2),
  ('X TSM 1', 'K3LH', 22, 2),
  ('X TSM 2', 'K3LH', 22, 2),
  ('X TSM 1', 'PDTO', 22, 4),
  ('X OTKP 1', 'Bahasa Indonesia', 23, 3),
  ('X TKJ 1', 'Bahasa Indonesia', 23, 3),
  ('X TKR 1', 'Bahasa Indonesia', 23, 3),
  ('X TSM 1', 'Bahasa Indonesia', 23, 3),
  ('XI OTKP 1', 'Bahasa Indonesia', 23, 3),
  ('XI OTKP 2', 'Bahasa Indonesia', 23, 3),
  ('XI TKJ 1', 'Bahasa Indonesia', 23, 3),
  ('XI TKJ 2', 'Bahasa Indonesia', 23, 3),
  ('XII TKJ 1', 'Bahasa Indonesia', 23, 3),
  ('XII TKJ 2', 'Bahasa Indonesia', 23, 3),
  ('XII TKR 1', 'Bahasa Indonesia', 23, 3),
  ('XII TKR 2', 'Bahasa Indonesia', 23, 3),
  ('XII TSM 1', 'Bahasa Indonesia', 23, 3),
  ('XII TSM 2', 'Bahasa Indonesia', 23, 3),
  ('X AK 1', 'Spreadsheet', 23, 2),
  ('XI AK 1', 'AK Keuangan', 23, 2),
  ('X AK 1', 'Pendidikan Agama dan Budi Pekerti', 24, 2),
  ('X TKJ 1', 'Pendidikan Agama dan Budi Pekerti', 24, 2),
  ('X TKR 2', 'Pendidikan Agama dan Budi Pekerti', 24, 2),
  ('X TSM 2', 'Pendidikan Agama dan Budi Pekerti', 24, 2),
  ('XI AK 1', 'Pendidikan Agama dan Budi Pekerti', 24, 2),
  ('XI OTKP 1', 'Pendidikan Agama dan Budi Pekerti', 24, 2),
  ('XI OTKP 2', 'Pendidikan Agama dan Budi Pekerti', 24, 2),
  ('XII AK 1', 'Pendidikan Agama dan Budi Pekerti', 24, 3),
  ('XII OTKP 1', 'Pendidikan Agama dan Budi Pekerti', 24, 2),
  ('XII OTKP 2', 'Pendidikan Agama dan Budi Pekerti', 24, 2),
  ('X TKJ 1', 'Dasar Jaringan Komputer', 25, 4),
  ('X TKJ 2', 'Dasar Jaringan Komputer', 25, 4),
  ('XII TKJ 1', 'Wide Area Network (WAN)', 25, 3),
  ('XII TKJ 2', 'Wide Area Network (WAN)', 25, 3),
  ('XI TKJ 1', 'Teknik Infrastruktur Jaringan', 25, 3),
  ('XI TKJ 2', 'Teknik Infrastruktur Jaringan', 25, 3),
  ('XI TKJ 1', 'Administrasi Sistem Jaringan', 25, 4),
  ('XI TKJ 2', 'Administrasi Sistem Jaringan', 25, 4),
  ('XII TKJ 1', 'Administrasi Sistem Jaringan', 25, 4),
  ('XII TKJ 2', 'Administrasi Sistem Jaringan', 25, 4),
  ('X TKR 1', 'Informatika', 25, 3),
  ('X TKR 2', 'Informatika', 25, 3),
  ('X TSM 1', 'Informatika', 25, 3),
  ('X TSM 2', 'Informatika', 25, 3),
  ('X TKJ 1', 'Tek Jaringan Komputer', 26, 3),
  ('X TKJ 2', 'Tek Jaringan Komputer', 26, 3),
  ('X TKJ 1', 'Bisnis Teknologi Informasi', 26, 3),
  ('X TKJ 2', 'Bisnis Teknologi Informasi', 26, 3),
  ('XI TKJ 1', 'Tek Layanan Jaringan', 26, 3),
  ('XI TKJ 2', 'Tek Layanan Jaringan', 26, 3),
  ('XI TKJ 1', 'Wide Area Network (WAN)', 26, 3),
  ('XI TKJ 2', 'Wide Area Network (WAN)', 26, 3),
  ('X AK 1', 'Informatika', 26, 3),
  ('X OTKP 1', 'Informatika', 26, 3),
  ('X OTKP 2', 'Informatika', 26, 3),
  ('X TKJ 1', 'Informatika', 26, 3),
  ('X TKJ 2', 'Informatika', 26, 3),
  ('X OTKP 1', 'Teknologi Perkantoran', 27, 3),
  ('X OTKP 2', 'Teknologi Perkantoran', 27, 3),
  ('X OTKP 1', 'OTK Humas', 27, 3),
  ('X OTKP 2', 'OTK Humas', 27, 3),
  ('XI OTKP 1', 'OTK Sarpras', 27, 2),
  ('XI OTKP 2', 'OTK Sarpras', 27, 2),
  ('XII OTKP 1', 'OTK Sarpras', 27, 4),
  ('XII OTKP 2', 'OTK Sarpras', 27, 4),
  ('XI OTKP 1', 'Kearsipan', 27, 2),
  ('XI OTKP 2', 'Kearsipan', 27, 2),
  ('X TKR 1', 'Bahasa Inggris', 28, 4),
  ('X TKR 2', 'Bahasa Inggris', 28, 4),
  ('X TSM 1', 'Bahasa Inggris', 28, 4),
  ('X TSM 2', 'Bahasa Inggris', 28, 4),
  ('XI TKJ 1', 'Bahasa Inggris', 28, 4),
  ('XI TKJ 2', 'Bahasa Inggris', 28, 4),
  ('X TKJ 2', 'Pendidikan Pancasila dan Kewarganegaraan', 29, 2),
  ('X TKR 1', 'Pendidikan Pancasila dan Kewarganegaraan', 29, 2),
  ('X TKR 2', 'Pendidikan Pancasila dan Kewarganegaraan', 29, 2),
  ('X TSM 1', 'Pendidikan Pancasila dan Kewarganegaraan', 29, 2),
  ('XII TKR 2', 'Pendidikan Pancasila dan Kewarganegaraan', 29, 2),
  ('XII TSM 1', 'Pendidikan Pancasila dan Kewarganegaraan', 29, 2),
  ('XII TSM 2', 'Pendidikan Pancasila dan Kewarganegaraan', 29, 2),
  ('X AK 1', 'Sejarah Indonesia', 29, 2),
  ('X OTKP 1', 'Sejarah Indonesia', 29, 2),
  ('X OTKP 2', 'Sejarah Indonesia', 29, 2),
  ('X TKJ 1', 'Sejarah Indonesia', 29, 2),
  ('X OTKP 1', 'Adm Umum', 30, 2),
  ('X OTKP 2', 'Adm Umum', 30, 2),
  ('XI AK 1', 'Adm Umum', 30, 2),
  ('X AK 1', 'IPAS', 30, 2),
  ('X OTKP 1', 'IPAS', 30, 2),
  ('X OTKP 2', 'IPAS', 30, 2),
  ('X TKJ 1', 'IPAS', 30, 2),
  ('X TKJ 2', 'IPAS', 30, 2),
  ('X TKR 1', 'IPAS', 30, 2),
  ('X TKR 2', 'IPAS', 30, 2),
  ('X TSM 1', 'IPAS', 30, 2),
  ('X TSM 2', 'IPAS', 30, 2),
  ('X AK 1', 'Komputer Akuntansi', 32, 2),
  ('XI AK 1', 'Komputer Akuntansi', 32, 2),
  ('XII AK 1', 'Komputer Akuntansi', 32, 3),
  ('X AK 1', 'Seni Budaya', 33, 2),
  ('X OTKP 1', 'Seni Budaya', 33, 2),
  ('X OTKP 2', 'Seni Budaya', 33, 2),
  ('X TKJ 1', 'Seni Budaya', 33, 2),
  ('X TKJ 2', 'Seni Budaya', 33, 2),
  ('X TKR 1', 'Seni Budaya', 33, 2),
  ('X TKR 2', 'Seni Budaya', 33, 2),
  ('X TSM 1', 'Seni Budaya', 33, 2),
  ('X TSM 2', 'Seni Budaya', 33, 2),
  ('XI AK 1', 'Seni Budaya', 33, 2),
  ('XI OTKP 1', 'Seni Budaya', 33, 2),
  ('XI OTKP 2', 'Seni Budaya', 33, 2),
  ('XI TKJ 1', 'Seni Budaya', 33, 2),
  ('XI TKJ 2', 'Seni Budaya', 33, 2),
  ('XI TKR 1', 'Seni Budaya', 33, 2),
  ('XI TKR 2', 'Seni Budaya', 33, 2),
  ('XI TSM 1', 'Seni Budaya', 33, 2),
  ('XI TSM 2', 'Seni Budaya', 33, 2),
  ('XII AK 1', 'Seni Budaya', 33, 2),
  ('XII OTKP 1', 'Seni Budaya', 33, 2),
  ('XII OTKP 2', 'Seni Budaya', 33, 2),
  ('XII TKJ 1', 'Seni Budaya', 33, 2),
  ('XII TKJ 2', 'Seni Budaya', 33, 2),
  ('XII TKR 1', 'Seni Budaya', 33, 2),
  ('XII TKR 2', 'Seni Budaya', 33, 2),
  ('XII TSM 1', 'Seni Budaya', 33, 2),
  ('XII TSM 2', 'Seni Budaya', 33, 2),
  ('X OTKP 1', 'Bahasa Inggris', 34, 4),
  ('X OTKP 2', 'Bahasa Inggris', 34, 4),
  ('X TKJ 1', 'Bahasa Inggris', 34, 4),
  ('X TKJ 2', 'Bahasa Inggris', 34, 4),
  ('XI OTKP 1', 'Bahasa Inggris', 34, 4),
  ('XI OTKP 2', 'Bahasa Inggris', 34, 4),
  ('XII TKR 1', 'Bahasa Inggris', 34, 4),
  ('XII TKR 2', 'Bahasa Inggris', 34, 4),
  ('XII TSM 1', 'Bahasa Inggris', 34, 4),
  ('XII TSM 2', 'Bahasa Inggris', 34, 4),
  ('X AK 1', 'Matematika', 35, 5),
  ('X OTKP 1', 'Matematika', 35, 5),
  ('X TKJ 1', 'Matematika', 35, 5),
  ('X TKJ 2', 'Matematika', 35, 5),
  ('XI TKR 1', 'Matematika', 35, 5),
  ('XI TKR 2', 'Matematika', 35, 5),
  ('X AK 1', 'Bahasa Indonesia', 36, 3),
  ('XI AK 1', 'Bahasa Indonesia', 36, 2),
  ('XI TKR 1', 'Bahasa Indonesia', 36, 3),
  ('XI TKR 2', 'Bahasa Indonesia', 36, 3),
  ('XI TSM 1', 'Bahasa Indonesia', 36, 3),
  ('XI TSM 2', 'Bahasa Indonesia', 36, 3),
  ('XII AK 1', 'Bahasa Indonesia', 36, 3),
  ('XII OTKP 1', 'Bahasa Indonesia', 36, 3),
  ('XII OTKP 2', 'Bahasa Indonesia', 36, 3),
  ('XII TKJ 1', 'Bahasa Indonesia', 36, 3),
  ('XII TKJ 2', 'Bahasa Indonesia', 36, 3),
  ('X TSM 2', 'TDO', 37, 4),
  ('X TKR 2', 'PDTO', 37, 4),
  ('X TKJ 1', 'K3LH', 37, 3),
  ('XI TSM 1', 'Main. Mesin Kendaraan', 37, 5),
  ('XI TSM 2', 'Main. Mesin Kendaraan', 37, 5),
  ('X AK 1', 'Pendidikan Pancasila dan Kewarganegaraan', 5, 2),
  ('X AK 1', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 3, 2),
  ('X AK 1', 'Etika Profesi', 11, 2),
  ('X AK 1', 'Akuntansi Dasar', 7, 3),
  ('X AK 1', 'Perbankan Dasar', 11, 2),
  ('X OTKP 1', 'Pendidikan Pancasila dan Kewarganegaraan', 12, 2),
  ('X OTKP 1', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 9, 2),
  ('X OTKP 1', 'Korespondensi', 8, 3),
  ('X OTKP 2', 'Pendidikan Pancasila dan Kewarganegaraan', 12, 2),
  ('X OTKP 2', 'Bahasa Indonesia', 13, 3),
  ('X OTKP 2', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 10, 2),
  ('X OTKP 2', 'Korespondensi', 8, 3),
  ('X TKJ 1', 'Pendidikan Pancasila dan Kewarganegaraan', 5, 2),
  ('X TKJ 1', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 10, 2),
  ('X TKJ 2', 'Bahasa Indonesia', 13, 3),
  ('X TKJ 2', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 9, 2),
  ('X TKR 1', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 3, 2),
  ('X TKR 2', 'Bahasa Indonesia', 13, 3),
  ('X TKR 2', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 3, 2),
  ('X TSM 1', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 9, 2),
  ('X TSM 1', 'Sejarah Indonesia', 11, 2),
  ('X TSM 2', 'Pendidikan Pancasila dan Kewarganegaraan', 5, 2),
  ('X TSM 2', 'Bahasa Indonesia', 13, 3),
  ('X TSM 2', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 10, 2),
  ('X TSM 2', 'Sejarah Indonesia', 11, 2),
  ('XI AK 1', 'Pendidikan Pancasila dan Kewarganegaraan', 12, 2),
  ('XI AK 1', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 10, 2),
  ('XI AK 1', 'Sejarah Indonesia', 11, 2),
  ('XI AK 1', 'Ekonomi Bisnis', 7, 2),
  ('XI AK 1', 'Praktikum Akuntansi Perusahaan Jasa, Dagang dan Manufaktur', 7, 2),
  ('XI AK 1', 'AK Lembaga', 7, 2),
  ('XI AK 1', 'PKK', 6, 3),
  ('XI OTKP 1', 'Pendidikan Pancasila dan Kewarganegaraan', 12, 2),
  ('XI OTKP 1', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 9, 2),
  ('XI OTKP 1', 'Sejarah Indonesia', 11, 2),
  ('XI OTKP 1', 'Matematika', 2, 5),
  ('XI OTKP 1', 'OTK Keuangan', 7, 2),
  ('XI OTKP 1', 'OTK Humas', 8, 3),
  ('XI OTKP 1', 'PKK', 6, 3),
  ('XI OTKP 2', 'Pendidikan Pancasila dan Kewarganegaraan', 5, 2),
  ('XI OTKP 2', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 3, 2),
  ('XI OTKP 2', 'Sejarah Indonesia', 11, 2),
  ('XI OTKP 2', 'Matematika', 4, 5),
  ('XI OTKP 2', 'OTK Keuangan', 7, 2),
  ('XI OTKP 2', 'OTK Humas', 8, 3),
  ('XI OTKP 2', 'PKK', 6, 3),
  ('XI TKJ 1', 'Pendidikan Pancasila dan Kewarganegaraan', 5, 2),
  ('XI TKJ 1', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 3, 2),
  ('XI TKJ 1', 'Sejarah Indonesia', 11, 2),
  ('XI TKJ 1', 'Matematika', 4, 5),
  ('XI TKJ 1', 'PKK', 6, 3),
  ('XI TKJ 2', 'Pendidikan Pancasila dan Kewarganegaraan', 12, 2),
  ('XI TKJ 2', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 9, 2),
  ('XI TKJ 2', 'Sejarah Indonesia', 11, 2),
  ('XI TKJ 2', 'Matematika', 2, 5),
  ('XI TKJ 2', 'PKK', 6, 3),
  ('XI TKR 1', 'Pendidikan Pancasila dan Kewarganegaraan', 12, 2),
  ('XI TKR 1', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 10, 2),
  ('XI TKR 1', 'PKK', 6, 3),
  ('XI TKR 2', 'Pendidikan Pancasila dan Kewarganegaraan', 5, 2),
  ('XI TKR 2', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 10, 2),
  ('XI TKR 2', 'PKK', 6, 3),
  ('XI TSM 1', 'Pendidikan Pancasila dan Kewarganegaraan', 5, 2),
  ('XI TSM 1', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 9, 2),
  ('XI TSM 1', 'PKK', 11, 3),
  ('XI TSM 2', 'Pendidikan Pancasila dan Kewarganegaraan', 12, 2),
  ('XI TSM 2', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 3, 2),
  ('XI TSM 2', 'PKK', 11, 3),
  ('XII AK 1', 'Pendidikan Pancasila dan Kewarganegaraan', 12, 2),
  ('XII AK 1', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 3, 2),
  ('XII AK 1', 'Sejarah Indonesia', 11, 2),
  ('XII AK 1', 'Praktikum Akuntansi Perusahaan Jasa, Dagang dan Manufaktur', 7, 4),
  ('XII AK 1', 'AK Lembaga', 7, 3),
  ('XII AK 1', 'AK Keuangan', 23, 3),
  ('XII AK 1', 'PKK', 6, 3),
  ('XII OTKP 1', 'Pendidikan Pancasila dan Kewarganegaraan', 5, 2),
  ('XII OTKP 1', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 9, 2),
  ('XII OTKP 1', 'Sejarah Indonesia', 11, 2),
  ('XII OTKP 1', 'Matematika', 2, 5),
  ('XII OTKP 1', 'OTK Keuangan', 7, 4),
  ('XII OTKP 1', 'OTK Humas', 8, 4),
  ('XII OTKP 1', 'PKK', 6, 3),
  ('XII OTKP 2', 'Pendidikan Pancasila dan Kewarganegaraan', 5, 2),
  ('XII OTKP 2', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 10, 2),
  ('XII OTKP 2', 'Sejarah Indonesia', 11, 2),
  ('XII OTKP 2', 'Matematika', 4, 5),
  ('XII OTKP 2', 'OTK Keuangan', 7, 4),
  ('XII OTKP 2', 'OTK Humas', 8, 4),
  ('XII OTKP 2', 'PKK', 6, 3),
  ('XII TKJ 1', 'Pendidikan Pancasila dan Kewarganegaraan', 12, 2),
  ('XII TKJ 1', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 10, 2),
  ('XII TKJ 1', 'Sejarah Indonesia', 11, 2),
  ('XII TKJ 1', 'PKK', 6, 3),
  ('XII TKJ 2', 'Pendidikan Pancasila dan Kewarganegaraan', 12, 2),
  ('XII TKJ 2', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 9, 2),
  ('XII TKJ 2', 'Sejarah Indonesia', 11, 2),
  ('XII TKJ 2', 'PKK', 6, 3),
  ('XII TKR 1', 'Pendidikan Pancasila dan Kewarganegaraan', 5, 2),
  ('XII TKR 1', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 3, 2),
  ('XII TKR 1', 'PKK', 11, 3),
  ('XII TKR 2', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 3, 2),
  ('XII TKR 2', 'PKK', 6, 3),
  ('XII TSM 1', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 9, 2),
  ('XII TSM 1', 'Matematika', 4, 5),
  ('XII TSM 1', 'PKK', 11, 3),
  ('XII TSM 2', 'Pendidikan Jasmani, Olah Raga & Kesehatan', 10, 2),
  ('XII TSM 2', 'Matematika', 2, 5),
  ('XII TSM 2', 'PKK', 6, 3)
) AS data(nama_kelas, nama_mapel, kode_guru, durasi_jp)
JOIN classes c ON c.nama_kelas = data.nama_kelas
JOIN subjects s ON s.nama_mapel = data.nama_mapel
LEFT JOIN teachers t ON t.kode_guru = data.kode_guru;