from backend.database import set_thread_branch, get_db_connection, db_fetchall

print("==================================================")
print(" 1. JAKARTA DATABASE CHECK")
print("==================================================")
set_thread_branch('jakarta')
conn_j = get_db_connection(branch='jakarta')
tj = db_fetchall(conn_j, "SELECT kode_guru, nama_guru FROM teachers ORDER BY kode_guru")
cj = db_fetchall(conn_j, "SELECT nama_kelas, shift_operasional, tingkat, jurusan FROM classes ORDER BY id_kelas")
sj = db_fetchall(conn_j, "SELECT nama_mapel FROM subjects")
tsj = db_fetchall(conn_j, "SELECT * FROM teacher_subjects")
csj = db_fetchall(conn_j, "SELECT * FROM class_subjects")
conn_j.close()

print("Teachers Count: %d" % len(tj))
print("Classes Count: %d" % len(cj))
print("Subjects Count: %d" % len(sj))
print("Teacher-Subjects Count: %d" % len(tsj))
print("Class-Subjects Count: %d" % len(csj))
print("Sample Teachers: %s" % ", ".join([t['nama_guru'] for t in tj[1:6]]))
print("Sample Classes: %s" % ", ".join([c['nama_kelas'] for c in cj[:6]]))

print("\n==================================================")
print(" 2. BEKASI DATABASE CHECK")
print("==================================================")
set_thread_branch('bekasi')
conn_b = get_db_connection(branch='bekasi')
tb = db_fetchall(conn_b, "SELECT kode_guru, nama_guru FROM teachers ORDER BY kode_guru")
cb = db_fetchall(conn_b, "SELECT nama_kelas, shift_operasional, tingkat, jurusan FROM classes ORDER BY id_kelas")
sb = db_fetchall(conn_b, "SELECT nama_mapel FROM subjects")
tsb = db_fetchall(conn_b, "SELECT * FROM teacher_subjects")
csb = db_fetchall(conn_b, "SELECT * FROM class_subjects")
conn_b.close()

print("Teachers Count: %d" % len(tb))
print("Classes Count: %d" % len(cb))
print("Subjects Count: %d" % len(sb))
print("Teacher-Subjects Count: %d" % len(tsb))
print("Class-Subjects Count: %d" % len(csb))
print("Sample Teachers: %s" % ", ".join([t['nama_guru'] for t in tb[1:6]]))
print("Sample Classes: %s" % ", ".join([c['nama_kelas'] for c in cb[:6]]))
